//! What a conversation is *about*, in one short line.
//!
//! # Why this exists
//!
//! Everything else osm records about a conversation identifies it — a kind, a
//! UUID, a project directory — and none of it says what it is *for*. The
//! maintainer's menu showed eight sessions reading `4 panes · 4 agents ·
//! workspace 4`, which is true of most of them at once. Their words: *"for me
//! there is no special information what is in particular session. we should
//! have option to go deep and try to grab the session goal."*
//!
//! # The two sources, and the difference between them
//!
//! * [`Source::Agent`] — the agent named the conversation itself. Claude Code
//!   writes `{"type":"ai-title","aiTitle":…}` records into its transcript and
//!   *revises* them as the conversation goes on (386 of them in the largest
//!   transcript on the maintainer's machine), so the last one is the current
//!   one. A title is not transcript content: it is the agent's own label for
//!   the whole conversation.
//!
//! * [`Source::FirstPrompt`] — one truncated line of the first thing the user
//!   typed. This **is** transcript content, and using it is a deliberate
//!   relaxation of the rule that osm displays and stores titles and ids only
//!   (see `docs/design.md`). It is confined to what that relaxation can
//!   justify: a single line, at most [`MAX_CHARS`] characters, from the user's
//!   own opening message and never from a reply, a tool result, or the agent's
//!   machinery — and never from a conversation osm cannot attribute.
//!
//!   It is not optional decoration. Codex writes no title of its own at all,
//!   and 2383 of the 2494 conversations on the maintainer's machine are
//!   Codex's; three of the newest ten Claude transcripts have no `ai-title`
//!   either. Without the fallback the feature would be blank for most rows,
//!   and a blank goal reads as "this session has no purpose".
//!
//! Which source a title came from travels with it everywhere — `osm agents
//! --json`, `osm status --json`, the database, the menu — so nobody has to
//! guess whether they are reading the agent's words or the user's.
//!
//! # Bounded reads, always
//!
//! The stores are 14 GB (Codex) and 1.4 GB (Claude) on the maintainer's
//! machine. Nothing here reads a whole file: a title comes out of a bounded
//! suffix and a prompt out of a bounded prefix, both capped in bytes
//! regardless of the file's size or whether it contains a newline at all. The
//! bounds are sized from that machine's own numbers, and are stated on the
//! constants. What falls outside them is reported as *no title*, never as a
//! reason to read more.

use super::AgentKind;
use std::io::{Read, Seek, SeekFrom};
use std::path::Path;

/// The longest a title is ever allowed to be.
///
/// A bar popup is 420 px wide and a row already carries a name and a set of
/// counts. Past this the text is not a title, it is a message body on a
/// popup — which is the thing a prompt-derived title must never become.
pub const MAX_CHARS: usize = 120;

/// How much of the *end* of a Claude transcript is read when looking for the
/// title the agent wrote.
///
/// Claude rewrites the title as the conversation goes on, so the current one
/// is near the end. Measured over every titled transcript in a 250-file sample
/// of the maintainer's store, the last `ai-title` sat between 1.2 KB and
/// 14.6 KB from the end of the file; 256 KiB is an order of magnitude of head
/// room over the worst of them, and 0.02% of the largest transcript there.
const CLAUDE_TITLE_SUFFIX_BYTES: u64 = 256 * 1024;

/// How much of the *start* of a Claude transcript is read when looking for
/// the first thing the user typed.
///
/// It arrives after the session's metadata records and whatever the start-up
/// hooks attached: median 18 KB into the file on the maintainer's machine,
/// 26 KB at the worst of 80 measured.
const CLAUDE_PROMPT_PREFIX_BYTES: u64 = 128 * 1024;

/// How much of the start of a Codex rollout is read.
///
/// Codex's opening records are its own: base instructions, a plugin listing,
/// the project's `AGENTS.md`. They are large and they are growing — over the
/// newest 200 rollouts on the maintainer's machine the user's first message
/// sat 98 KB into the file at the median and 363 KB at the worst — so this
/// bound is four times the Claude one and still a fraction of a 6 MB rollout.
const CODEX_PROMPT_PREFIX_BYTES: u64 = 512 * 1024;

/// Openings that belong to the agent's machinery rather than to the user.
///
/// Claude Code records a slash command, a local-command caveat and a hook's
/// injected context as *user* messages, because that is what they are to the
/// model. They are not what the person sitting there typed, and a menu full of
/// rows reading "Caveat: The messages below were generated by the user while
/// running local commands" says nothing about any of them — five of the newest
/// twelve transcripts on the maintainer's machine open with exactly that.
const MACHINERY_OPENINGS: [&str; 5] = [
    "<command-name>",
    "<command-message>",
    "<local-command-caveat>",
    "<system-reminder>",
    "Caveat:",
];

/// What a title may be derived from.
///
/// The whole of `privacy.prompt_titles`, in the form the extractor obeys.
/// [`Policy::AgentOnly`] does not read a message at all — not to discard it
/// afterwards, but by never scanning for one: "osm read your first prompt and
/// then threw it away" is not what someone who switched this off asked for.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Policy {
    /// Only what the agent wrote about the conversation itself.
    AgentOnly,
    /// That, and — where the agent wrote nothing — one truncated line of the
    /// user's first message.
    AgentOrFirstPrompt,
}

impl Policy {
    /// The policy `privacy` asks for.
    pub fn of(privacy: &crate::config::PrivacyCfg) -> Policy {
        if privacy.prompt_titles {
            Policy::AgentOrFirstPrompt
        } else {
            Policy::AgentOnly
        }
    }

    fn reads_prompts(&self) -> bool {
        matches!(self, Policy::AgentOrFirstPrompt)
    }
}

/// Where a title came from. Never inferred by a reader: it is recorded
/// alongside the text.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Source {
    /// The agent's own name for the conversation.
    Agent,
    /// One truncated line of the user's first message.
    FirstPrompt,
}

impl Source {
    /// The stable token used in JSON and in the database.
    pub fn as_str(&self) -> &'static str {
        match self {
            Source::Agent => "agent",
            Source::FirstPrompt => "first_prompt",
        }
    }

    /// Exact match only; an unknown token is not a source.
    pub fn parse(s: &str) -> Option<Source> {
        match s {
            "agent" => Some(Source::Agent),
            "first_prompt" => Some(Source::FirstPrompt),
            _ => None,
        }
    }
}

/// One line saying what a conversation is about, and where that line came
/// from.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Title {
    pub text: String,
    pub source: Source,
}

/// Characters that go along with the control characters, because they are
/// drawn as nothing and can change what the rest of the line says.
///
/// [`char::is_control`] is the Unicode `Cc` category: C0 and C1, the escape
/// sequences and the stray newlines a pasted prompt is full of. It leaves
/// every *format* character (`Cf`) in place, and those are the ones that
/// matter in a panel:
///
/// * **U+202E** RIGHT-TO-LEFT OVERRIDE and its relatives reverse the run that
///   follows them, so a title of `Open <U+202E>gnp.eciovni` is *drawn* as
///   `Open invoice.png` while the title osm recorded says something else. What
///   is stored and what is drawn have to be the same string. (Written here as
///   an escape on purpose: a source file that contains one is as misleading to
///   read as the panel was.)
/// * **U+2066…U+2069**, the isolates, do the same job with a scope, and are
///   the ones a modern renderer actually honours.
/// * **U+200B**, **U+2060**, **U+FEFF** and the tag characters at **U+E0000**
///   are drawn as nothing at all. They split a word that must not be split,
///   and they can carry a whole second sentence inside a title that looks
///   short.
///
/// A title is one line of somebody else's file rendered in the maintainer's
/// bar. It has no use for any of them, and a panel that shows something other
/// than what osm recorded is the defect this whole plugin is built around.
///
/// **U+FE00…U+FE0F — the variation selectors — are deliberately kept.** They
/// choose a presentation (text or emoji) for the visible character before
/// them; they cannot hide or reorder anything, and stripping them would change
/// how an ordinary emoji in a title is drawn for no safety at all. Their
/// supplement at U+E0100…U+E01EF is inside the tag block below and does go:
/// it selects among rare CJK ideographic variants, and it sits in the same
/// range as the tag characters, which are an invisible alphabet.
fn is_hidden_formatting(ch: char) -> bool {
    matches!(
        ch as u32,
        0x00AD                  // soft hyphen
            | 0x061C            // Arabic letter mark
            | 0x180E            // Mongolian vowel separator
            | 0x200B..=0x200F   // zero-width space/joiners, LRM, RLM
            | 0x202A..=0x202E   // embeddings, overrides, PDF
            | 0x2060..=0x2064   // word joiner, invisible operators
            | 0x2066..=0x2069   // isolates, and the pop that ends them
            | 0xFEFF            // zero-width no-break space (BOM)
            | 0xFFF9..=0xFFFB   // interlinear annotation
            | 0x110BD | 0x110CD // Kaithi number signs
            | 0x13430..=0x1343F // Egyptian hieroglyph format controls
            | 0x1BCA0..=0x1BCA3 // shorthand format controls
            | 0x1D173..=0x1D17A // musical formatting
            | 0xE0000..=0xE0FFF // tags, and the variation selectors supplement
    )
}

impl Title {
    /// A title from `raw`, reduced to one bounded line, or `None` when there
    /// is nothing left of it.
    ///
    /// Whitespace — including the newlines a pasted prompt is full of — is
    /// collapsed to single spaces, and control characters go entirely: this
    /// text is drawn in a panel and printed in JSON, and an escape sequence
    /// from a conversation osm did not write has no business in either. So do
    /// the format characters [`is_hidden_formatting`] names, which are the
    /// ones that reverse or conceal the rest of the line.
    pub fn new(raw: &str, source: Source) -> Option<Title> {
        let mut text = String::new();
        let mut space = false;
        for ch in raw.chars() {
            if ch.is_whitespace() {
                space = !text.is_empty();
                continue;
            }
            if ch.is_control() || is_hidden_formatting(ch) {
                continue;
            }
            if space {
                text.push(' ');
                space = false;
            }
            text.push(ch);
        }
        if text.is_empty() {
            return None;
        }
        if text.chars().count() > MAX_CHARS {
            // The ellipsis is part of the budget, and it is what tells a
            // reader they are looking at the head of something longer rather
            // than at the whole of what was asked.
            text = text.chars().take(MAX_CHARS - 1).collect::<String>() + "…";
        }
        Some(Title { text, source })
    }
}

/// Read forward from the start of `path`, one complete line at a time, and
/// return the first thing `answer` makes of a line — reading at most `cap`
/// bytes whatever happens, and stopping the moment there is an answer.
///
/// Both halves matter, and they are different guarantees. The cap is a hard
/// bound on the read itself, never "read until something is found": a rollout
/// can be hundreds of megabytes and a corrupt one may hold no newline at all,
/// so the file handle itself is bounded (`take`) rather than the loop trusted
/// to stop. Stopping early is what makes the cap affordable: the first prompt
/// sits 98 KB into a Codex rollout at the median, and reading the remaining
/// 400 KB of the bound to confirm what is already known cost more than the
/// whole of the rest of `osm agents` on the maintainer's machine.
///
/// `needle` is the cheap half of the same idea. A prefix of a Codex rollout is
/// mostly base instructions and injected context — hundreds of kilobytes of
/// JSON with nothing in it this can use — and running a parser over all of it
/// took twelve seconds where a substring test over the raw bytes takes
/// milliseconds. A line without the needle cannot be the record being looked
/// for, so it is never parsed.
fn scan_prefix<T>(
    path: &Path,
    cap: u64,
    needle: &str,
    mut answer: impl FnMut(&serde_json::Value) -> Option<T>,
) -> Option<T> {
    use std::io::BufRead;
    // Never through a symlink, and never a special file: see
    // [`super::open_conversation_file`], and `tests/agent_hardening.rs`.
    let file = super::open_conversation_file(path).ok()?;
    let mut reader = std::io::BufReader::new(file.take(cap));
    let mut line = Vec::new();
    loop {
        line.clear();
        if reader.read_until(b'\n', &mut line).ok()? == 0 {
            return None;
        }
        // Lossy rather than a failure: one bad byte must not cost the record
        // it is in, let alone the ones after it.
        let text = String::from_utf8_lossy(&line);
        if !text.contains(needle) {
            continue;
        }
        // The last line of a capped read is routinely a record cut in half.
        // It fails to parse, which is the correct outcome.
        let Ok(value) = serde_json::from_str::<serde_json::Value>(text.trim_end()) else {
            continue;
        };
        if let Some(found) = answer(&value) {
            return Some(found);
        }
    }
}

/// At most `cap` bytes from the end of `path`, starting at a line boundary.
///
/// The first line of a suffix that did not start at the beginning of the file
/// is a fragment of whatever record straddles the cut. It is dropped rather
/// than parsed: half a record parses as nothing, which is harmless, but half
/// of one that happens to parse would be a title assembled out of two.
fn suffix(path: &Path, cap: u64) -> Option<Vec<u8>> {
    let mut file = super::open_conversation_file(path).ok()?;
    let len = file.metadata().ok()?.len();
    let whole_file = len <= cap;
    if !whole_file {
        file.seek(SeekFrom::Start(len - cap)).ok()?;
    }
    let mut buf = Vec::new();
    file.take(cap).read_to_end(&mut buf).ok()?;
    if !whole_file {
        match buf.iter().position(|&b| b == b'\n') {
            Some(at) => buf.drain(..=at),
            // No newline in the whole capped window: there is no complete
            // record in it, and nothing to read.
            None => return Some(Vec::new()),
        };
    }
    Some(buf)
}

/// Every complete JSON record in `bytes` that could be the one being looked
/// for, in order.
///
/// `needle` is a substring test over the raw line, for the same reason as in
/// [`scan_prefix`]: a line without it cannot be the record, and parsing every
/// line of a window to find that out is the difference between milliseconds
/// and seconds. A line that does not parse is skipped, not an error.
fn records<'a>(bytes: &'a [u8], needle: &'a str) -> impl Iterator<Item = serde_json::Value> + 'a {
    // Lossy rather than a UTF-8 failure for the whole buffer: one bad byte in
    // a 256 KiB window must not cost the title in the line before it.
    let text = String::from_utf8_lossy(bytes).into_owned();
    text.lines()
        .filter(|line| line.contains(needle))
        .filter_map(|line| serde_json::from_str::<serde_json::Value>(line).ok())
        .collect::<Vec<_>>()
        .into_iter()
}

/// Whether a record that carries a conversation id carries *this* one.
///
/// A record with no id at all is accepted: the file's name is what attributes
/// it, and that is the same attribution every other field osm reads out of
/// these stores rests on. A record that names a *different* conversation is
/// refused, which is the case this exists for — nothing from a conversation
/// osm cannot attribute may be shown against another.
fn attributed(value: &serde_json::Value, keys: &[&str], id: &str) -> bool {
    for key in keys {
        if let Some(found) = value.get(key).and_then(|v| v.as_str()) {
            return found == id;
        }
    }
    true
}

/// The text of a Claude message record's content, whether it is a bare string
/// or the array form.
///
/// Only `text` parts. A tool result or an image part is not something a user
/// typed and has no place in a title.
fn claude_message_text(record: &serde_json::Value) -> Option<&str> {
    let content = record.get("message")?.get("content")?;
    if let Some(s) = content.as_str() {
        return Some(s);
    }
    content.as_array()?.iter().find_map(|part| {
        (part.get("type").and_then(|v| v.as_str()) == Some("text"))
            .then(|| part.get("text").and_then(|v| v.as_str()))
            .flatten()
    })
}

/// The title of the Claude conversation `id`, whose transcript is at `path`.
///
/// The agent's own last `ai-title` first, and one line of the user's first
/// message only when there is none.
pub(crate) fn claude(path: &Path, id: &str, policy: Policy) -> Option<Title> {
    if let Some(bytes) = suffix(path, CLAUDE_TITLE_SUFFIX_BYTES) {
        let mut latest = None;
        for record in records(&bytes, "ai-title") {
            if record.get("type").and_then(|v| v.as_str()) != Some("ai-title") {
                continue;
            }
            if !attributed(&record, &["sessionId"], id) {
                continue;
            }
            if let Some(text) = record.get("aiTitle").and_then(|v| v.as_str()) {
                // Every one of these is a revision of the one before it, so
                // the last is the conversation's current name and the earlier
                // ones are history.
                latest = Title::new(text, Source::Agent).or(latest);
            }
        }
        if latest.is_some() {
            return latest;
        }
    }

    if !policy.reads_prompts() {
        return None;
    }
    scan_prefix(path, CLAUDE_PROMPT_PREFIX_BYTES, "\"user\"", |record| {
        if record.get("type").and_then(|v| v.as_str()) != Some("user") {
            return None;
        }
        // `isMeta` is Claude's own flag for a user-shaped record it wrote
        // itself; `isSidechain` marks a subagent's brief, which belongs to a
        // conversation the user never typed into.
        if record.get("isMeta").and_then(|v| v.as_bool()) == Some(true)
            || record.get("isSidechain").and_then(|v| v.as_bool()) == Some(true)
        {
            return None;
        }
        if !attributed(record, &["sessionId"], id) {
            return None;
        }
        let text = claude_message_text(record)?;
        if MACHINERY_OPENINGS
            .iter()
            .any(|m| text.trim_start().starts_with(m))
        {
            return None;
        }
        Title::new(text, Source::FirstPrompt)
    })
}

/// The title of the Codex conversation `id`, whose rollout is at `path`.
///
/// Codex writes no title of its own, so this is always the first prompt — the
/// `event_msg` / `user_message` record, which is the moment the user typed
/// something. The role-`user` messages before it are Codex's own preamble (a
/// plugin listing, the project's `AGENTS.md`), which is why the first
/// *message* in the file is deliberately not what is read.
pub(crate) fn codex(path: &Path, id: &str, policy: Policy) -> Option<Title> {
    // Codex has no title of its own to fall back to, so the strict policy
    // leaves every Codex conversation untitled, and says so rather than
    // reading a rollout it may not use.
    if !policy.reads_prompts() {
        return None;
    }
    // A rollout whose own metadata names another conversation is somebody
    // else's, and nothing in it may be shown against this one. `None` — no
    // `session_meta` inside the bound at all — is not a mismatch: the file's
    // name is what attributes it, exactly as it does for every other field
    // osm reads out of these stores.
    let mine = scan_prefix(
        path,
        CODEX_PROMPT_PREFIX_BYTES,
        "\"session_meta\"",
        |record| {
            if record.get("type").and_then(|v| v.as_str()) != Some("session_meta") {
                return None;
            }
            Some(attributed(
                record.get("payload")?,
                &["id", "session_id"],
                id,
            ))
        },
    );
    if mine == Some(false) {
        return None;
    }

    scan_prefix(path, CODEX_PROMPT_PREFIX_BYTES, "user_message", |record| {
        let payload = record.get("payload")?;
        if payload.get("type").and_then(|v| v.as_str()) != Some("user_message") {
            return None;
        }
        let text = payload.get("message").and_then(|v| v.as_str())?;
        Title::new(text, Source::FirstPrompt)
    })
}

/// The title of `id`'s conversation, dispatched on its kind.
///
/// `None` for an agent whose store osm does not read (OpenCode, whose
/// conversations it only ever hears about through that agent's CLI) and for
/// anything it cannot attribute.
pub fn of(kind: AgentKind, id: &str, store_path: Option<&str>, policy: Policy) -> Option<Title> {
    let path = Path::new(store_path?);
    match kind {
        AgentKind::Claude => claude(path, id, policy),
        AgentKind::Codex => codex(path, id, policy),
        AgentKind::OpenCode => None,
    }
}
